### ISSUE TITLE
ACMAPP: Create getPage method in SqlClient Class

### ISSUE THREAD

**Issue by sambutler1017** [cse-uprc/acm-app-microservice#10]
### Get Page Method
- This method will return a list of objects based on the query passed in.
- This ticket is very similar to ticket ACMAPP: #8, except this time it is returning a list of objects rather than a single object.
- This method will also use generics and take into account the ability to use`.query()` which is apart of the `JdbcTemplate` class

### Dependent Tickets:
- [ ] ACMAPP: #6
- [ ] ACMAPP: #8

**Comment by kwinborne** [comment]
Closed by #67
