### ISSUE TITLE
ACMAPP: Create Authentication Service Class

### ISSUE THREAD

**Issue by sambutler1017** [cse-uprc/acm-app-microservice#16]
### Authentication Service Class
- This class will help do the dirty work when validating that the user logging in is a real user or a user that is in our database and allowed to log in.
- When the user client is in place this class will call that client and pass in a userId, if it is a valid user then it will return the user's profile, otherwise, the client will throw an error.

### Dependencies:
- User Client

**Comment by kwinborne** [comment]
Closed by #73
