### ISSUE TITLE
ACMAPP: Add acm-library jar file into repo

### ISSUE THREAD

**Issue by sambutler1017** [cse-uprc/acm-app-microservice#28]
### Task
- Need to add the jar file produced from the `acm-library` and add it to the `.jars` folder of this repo.

### Process
- First need to pull down the latest pushes from the `acm-library` repo
- open the project in eclipse and right click on it and click export
- Then hit export as jar
- The place it in the .jars file of the `acm-app-microservice` repo

### Important
- The name of the jar needs to follow as such
   - `acm-library-1.0.0` - the version will be the only thing that changes
   - The version will always be the name of the current version and there will only ever be a single version of the acm`-library at all times. The only two files in there will be te mysqlConnector and the acm-library jar file.

**Comment by kwinborne** [comment]
Closed by #65
