### ISSUE TITLE
ACMAPP: Create SqlClient Service for executing Queries

### ISSUE THREAD

**Issue by sambutler1017** [cse-uprc/acm-app-microservice#6]
### SqlClient Class
- A class will need to be created in order to manage requests and be consistent throughout the application so that everyone is not doing their own thing when it comes to executing queries.
- This service will just be a skeleton for now.
- The end goal is to have methods that can process the main request that we will be dealing with:
   - `GET`
   - `POST`
   - `DELETE`
   - `PUT`
- A package can be created in the project called `com.acm.service.sql`
   - Then create a class called `SqlClient`
- The code below is what will need to be added first as a skeleton. This is a good starting place in what needs to be done.
```
@Component
@Service
public class SqlClient {

	private static JdbcTemplate jdbcTemplateObject;
	private static DriverManagerDataSource source = new DriverManagerDataSource();
}
```

**Comment by kwinborne** [comment]
Closed by #67
