### ISSUE TITLE
ACMAPP: Create Constructor in SqlClient to assign the appropriate config file based on the environment

### ISSUE THREAD

**Issue by sambutler1017** [cse-uprc/acm-app-microservice#8]
### Constructor Method
- The first thing to note is that ticket is dependent on ACMAPP: #6 
- Once that is complete then the constructor can be created in order to set the appropriate fields needed to make the right database calls based on the applications environment
- The following fields that need set for the data source variable are (These are on the `DriverManagerDataSource` object):
   - `source.setDriverClassName()`
   - `source.setUrl()`
   - `source.setUsername()`
   - `source.setPassword()`
- The data needed in order to get these fields can be retrieved by creating `Properties` object and creating a `FileInputStream` based on the currently active profile of the environment.
- The path to be used in the inputStream can be retrieved by using the active profile and called the `getPropertyFilePath()` method in order to get the current active profile config.
- It would look something like this:
```
Properties prop = new Properties();
try (InputStream input = new FileInputStream(ActiveProfile.getPropertyFilePath())) {
	prop.load(input);
} catch (IOException io) {
	io.printStackTrace();
}
```
- Once that property file is loaded then the data source fields can be set and a new instance of the `JdbcTemplate` can be created like so:
```
jdbcTemplateObject = new JdbcTemplate(source);
```

### Dependent Tickets:
- [x] ACMAPP: #6

**Comment by kwinborne** [comment]
Closed by #67
