### ISSUE TITLE
ACMAPP: Update getUserCredentials query to include first and last name in token

### ISSUE THREAD

**Issue by sambutler1017** [cse-uprc/acm-app-microservice#85]
### Update
- Need to add `uc.first_name` and `uc.last_name` to the query select for `getUserCredentials`
- The first and last name fields are required on the token and if they are not sent then the fields are set to null.
- This is what the decoded token looks like currently on development:
![image](https://user-images.githubusercontent.com/67570772/89341312-1a595f00-d66f-11ea-882b-2aae2b303013.png)

- This needs to be fixed before the `1.1.0` release on Friday

### Needed Changes
- Query needs to be modified to look like so:
   - File Location: `src/main/resources` under `dao.userDAO.acmsql`
```
SELECT
   uc.user_id,
   uc.username,
   uc.password,
   uc.first_name,
   uc.last_name
   . . .
```
- The mapper needs updated as well to have the following setters
  - File Location: `src/main/java` under `com.acm.app.user.mapper.UserCredentialMapper`
```
user.setFirstName(rs.getString("first_name"));
user.setLastName(rs.getString("last_name"));
```
- Along with these changes, make sure to update the changeLog with the addressed change.

**Comment by kwinborne** [comment]
Superseded by #121
