### ISSUE TITLE
ACMAPP: Create a getTemplate method in SqlClient Class

### ISSUE THREAD

**Issue by sambutler1017** [cse-uprc/acm-app-microservice#9]
### GetTemplate Method
- This method is what will get a single row from the database or whatever the first row from the database that is returned.
- This will need to be a generic method that will accept any object.
- This will take in two parameters:
   - `String`: The query string to be processed
   - `RowMapper<T>`: How it should map the return data
- Once that part is created then the contents of it are pretty simple. There is a `.query()` method on the `JdbcTemplate` class that we can use and takes in a string query parameter and a row mapper object.
- Since this will return a single row, on the end of the returning result we will want something like `.get(0)` since it returns a list.
- Before this can be done these task need to be in place first:

### Dependent Tickets:
- [ ] ACMAPP: #6 
- [ ] ACMAPP: #8

**Comment by kwinborne** [comment]
Closed by #69
